=== samhastings/datatypes/schema/article.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "https://datatypes.io/schema/article.json",
    "title": "Article",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9-]+$"
        },
        "title": {
            "type": "string"
        },
        "ddl": {
            "type": "object",
            "patternProperties": {
                "^(sql-92|mysql|mssql|oracle|postgresql|db2)$": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 1
                    }
                }
            },
            "additionalProperties": false
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["inaccurate", "incomplete", "proprietary"]
            }
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "visible": {
            "type": "boolean"
        },
        "related": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "further-reading": {
            "type": "object",
            "additionalProperties": {
                "type": "string",
                "format": "uri"
            }
        }
    },
    "additionalProperties": false,
    "required": ["id", "title", "ddl", "visible"]
}

=== samhastings/datatypes/datatypes/stripe-object-id/data.json
{
    "id": "stripe-object-id",
    "title": "Stripe object ID",
    "ddl": {
        "sql-92": [
            "VARCHAR(255) COLLATE utf8_bin"
        ],
        "mysql": [
            "VARCHAR(255) COLLATE utf8_bin"
        ]
    },
    "categories": ["colors"],
    "tags": ["inaccurate", "incomplete"],
    "keywords": [],
    "visible": true,
    "further-reading": {
        "Stripe documentation": "http://example.com/",
        "Stripe API reference": "http://example.com/"
    }
}
